[build]
  base = "client"
  command = "yarn && yarn build"
  publish = "dist"

# Canonicalize www → root (must come before SPA fallback)
[[redirects]]
  from = "/*"
  to = "https://nairalancers.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["www.nairalancers.com"] }

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: proxy API through Netlify if you prefer relative /api calls in the client
# Uncomment and set your API domain if you want to proxy
# [[redirects]]
#   from = "/api/*"
#   to = "https://api.example.com/:splat"
#   status = 200
#   force = true
#   headers = { X-Forwarded-Host = ":host" }
