// src/data/categoriesData.js

export const categories = [
  {
    name: "Graphics & Design",
    subs: [
      "Logo Design",
      "Brand Style Guides",
      "Game Art",
      "Graphics for Streamers",
      "Business Cards & Stationery",
      "Illustration",
      "Pattern Design",
      "Brochure Design",
      "Poster Design",
      "Flyer Design",
      "Book Design",
      "Album Cover Design",
      "Podcast Cover Art",
      "Social Media Design",
      "Web Banners",
      "Signage Design",
      "Email Design",
      "Icon Design",
      "Image Editing",
      "Presentation Design",
      "Infographic Design",
      "Vector Tracing",
      "T-Shirt & Merchandise",
      "Fashion Design",
      "Jewelry Design",
      "Industrial & Product Design",
      "Character Modeling",
      "Architectural Design",
      "Landscape Design",
      "Building Engineering",
      "Interior Design",
      "Trade Booth Design",
      "Other"
    ]
  },
  {
    name: "Digital Marketing",
    subs: [
      "Search Engine Optimization (SEO)",
      "Generative Engine Optimization",
      "Search Engine Marketing (SEM)",
      "Local SEO",
      "E-Commerce SEO",
      "Video SEO",
      "Social Media Marketing",
      "Paid Social Media",
      "Social Commerce",
      "Influencer Marketing",
      "Online Communities",
      "Video Marketing",
      "E-Commerce Marketing",
      "Email Marketing",
      "Email Automations",
      "Marketing Automation",
      "Guest Posting",
      "Affiliate Marketing",
      "Display Advertising",
      "Public Relations",
      "Crowdfunding",
      "Text Message Marketing",
      "Marketing Strategy",
      "Brand Strategy",
      "UGC Strategy",
      "Marketing Concepts & Ideation",
      "Conversion Rate Optimization (CRO)",
      "Conscious Branding & Marketing",
      "Web Analytics",
      "Marketing Advice",
      "Music Promotion",
      "Podcast Marketing",
      "Mobile App Marketing",
      "Book & eBook Marketing",
      "Self-Publish Your Book"
    ]
  },
  {
    name: "Writing & Translation",
    subs: [
      "Articles & Blog Posts",
      "Content Strategy",
      "Website Content",
      "Scriptwriting",
      "Creative Writing",
      "Podcast Writing",
      "Speechwriting",
      "Research & Summaries",
      "Proofreading & Editing",
      "Academic Support",
      "AI Content Editing",
      "Writing Advice",
      "Book & eBook Writing",
      "Book Editing",
      "Beta Reading",
      "Book Publishing",
      "Career Writing",
      "Resume Writing",
      "Cover Letters",
      "LinkedIn Profiles",
      "Job Descriptions",
      "Brand Voice & Tone",
      "Slogans",
      "Product Descriptions",
      "Ad Copy",
      "Sales Copy",
      "Press Releases",
      "UX Writing",
      "eLearning Content Development",
      "Technical Writing",
      "Handwriting",
      "Translation",
      "Localization",
      "Transcription",
      "Interpretation"
    ]
  },
  {
    name: "Video & Animation",
    subs: [
      "Video Editing",
      "Visual Effects",
      "Intro & Outro Videos",
      "Video Repurposing",
      "Video Templates Editing",
      "Subtitles & Captions",
      "Social & Marketing Videos",
      "UGC Videos",
      "TikTok UGC Videos",
      "UGC Ads",
      "Spokesperson Videos",
      "Logo Animation",
      "Lottie & Web Animation",
      "Text Animation",
      "Character Animation",
      "Animated GIFs",
      "Animation for Kids",
      "Animation for Streamers",
      "Rigging",
      "NFT Animation",
      "Filmed Video Production",
      "Animated Explainers",
      "Live Action Explainers",
      "Screencasting Videos",
      "eLearning Video Production",
      "Crowdfunding Videos",
      "Product Videos",
      "3D Product Animation",
      "E-Commerce Product Videos",
      "Corporate Videos",
      "App & Website Previews",
      "AI Video Art",
      "AI Music Videos",
      "AI Video Avatars",
      "Virtual & Streaming Avatars",
      "Article-to-Video",
      "Game Trailers",
      "Game Recordings & Guides",
      "Meditation Videos",
      "Real Estate Promos",
      "Book Trailers",
      "Video Advice",
      "Other"
    ]
  },
  {
    name: "Music & Audio",
    subs: [
      "Music Production & Writing",
      "Audio Engineering & Post Production",
      "Voice Over & Narration",
      "Podcast Production",
      "Audiobook Production",
      "Audio Ads Production",
      "Voice Synthesis & AI",
      "DJing",
      "Sound Design",
      "Meditation Music",
      "Audio Logo & Sonic Branding",
      "Custom Patches & Samples",
      "Audio Plugin Development",
      "Online Music Lessons",
      "Music Transcription",
      "Music & Audio Advice"
    ]
  },
  {
    name: "Photography",
    subs: [
      "Product Photography",
      "Food Photography",
      "Lifestyle & Fashion Photography",
      "Portrait Photography",
      "Event Photography",
      "Real Estate Photography",
      "Scenic Photography",
      "Drone Photography",
      "Local Photography",
      "Photo Preset Creation",
      "Photography Advice",
      "Other"
    ]
  },
  {
    name: "Programming & Tech",
    subs: [
      "Website Development",
      "Website Maintenance",
      "WordPress",
      "Shopify",
      "Custom Websites",
      "Landing Pages",
      "Dropshipping Websites",
      "Web Applications",
      "Desktop Applications",
      "Game Development",
      "Chatbot Development",
      "Browser Extensions",
      "Software Development",
      "AI Development",
      "APIs & Integrations",
      "Scripting",
      "Plugins Development",
      "Mobile App Development",
      "Cross-platform Apps",
      "Android Development",
      "iOS Development",
      "Mobile App Maintenance",
      "Wix",
      "Webflow",
      "GoDaddy",
      "Squarespace",
      "WooCommerce",
      "Cloud Computing",
      "DevOps Engineering",
      "Cybersecurity",
      "Blockchain & Cryptocurrency",
      "Decentralized Apps",
      "Coin Design & Tokenization",
      "Blockchain Security & Auditing",
      "Exchange Platforms",
      "Electronics Engineering",
      "QA & Review",
      "User Testing",
      "Online Coding Lessons"
    ]
  },
  {
    name: "Business",
    subs: [
      "Business Formation & Registration",
      "Market Research",
      "Business Plans",
      "Business Consulting",
      "HR Consulting",
      "AI Consulting",
      "Operations & Management",
      "Virtual Assistant",
      "Project Management",
      "Software Management",
      "E-Commerce Management",
      "Supply Chain Management",
      "Event Management",
      "Product Management",
      "Intellectual Property Management",
      "Legal Documents & Contracts",
      "Legal Research",
      "General Legal Advice",
      "Sales",
      "Lead Generation",
      "Call Center & Calling",
      "Customer Experience Management (CXM)",
      "Data Visualization",
      "Data Analytics",
      "Data Scraping",
      "Presentations",
      "Online Investigations",
      "Sustainability Consulting",
      "Game Concept Design",
      "Other"
    ]
  },
  {
    name: "Finance",
    subs: [
      "Accounting Services",
      "Fractional CFO Services",
      "Financial Reporting",
      "Bookkeeping",
      "Payroll Management",
      "Due Diligence",
      "Valuation",
      "M&A Advisory",
      "Tax Consulting",
      "Tax Returns",
      "Tax Identification",
      "Tax Planning",
      "Financial Planning & Analysis",
      "Budgeting",
      "Forecasting",
      "Financial Modeling",
      "Stock Analysis",
      "Personal Finance & Wealth Management",
      "Investments Advisory",
      "Online Trading Lessons",
      "Retirement Advisory",
      "Financial Coaching",
      "Insurance Advisory",
      "Fundraising & Investor Sourcing",
      "Funding Pitch Presentations",
      "Fundraising Consultation",
      "Banking",
      "Mortgage Advisory",
      "Loan Advisory",
      "Credit Score Advisory",
      "Bank Account Opening"
    ]
  },
  {
    name: "AI Services",
    subs: [/* Expand with specific subcategories as needed */]
  },
  {
    name: "Consulting",
    subs: [/* Expand with specific subcategories as needed */]
  },
  {
    name: "Data",
    subs: [/* Expand with specific subcategories as needed */]
  },
  {
    name: "Personal Growth & Hobbies",
    subs: [/* Expand with specific subcategories as needed */]
  },
  {
    name: "End-to-End Projects",
    subs: [/* Expand if needed */]
  },
  {
    name: "Service Catalog",
    subs: [/* Expand if needed */]
  }
];
